name       : inetutils
version    : '2.4'
release    : 11
source     :
    - https://ftp.gnu.org/gnu/inetutils/inetutils-2.4.tar.xz : 1789d6b1b1a57dfe2a7ab7b533ee9f5dfd9cbf5b59bb1bb3c2612ed08d0f68b2
homepage   : https://www.gnu.org/software/inetutils
license    :
    - GPL-3.0-or-later
summary    :
    - A collection of common network programs
    - ^ifconfig : The deprecated ifconfig command
description:
    - A collection of common network programs
    - ^ifconfig : The deprecated ifconfig command.
component  :
    - system.base
    - ^ifconfig : network.util
patterns   :
    - ^ifconfig :
        - /usr/bin/ifconfig
        - /usr/share/man/man1/ifconfig.1
builddeps  :
    - help2man
optimize   :
    - lto
setup      : |
    %patch -p1 -i $pkgfiles/security/CVE-2023-40303.patch

    %configure --disable-logger \
               --disable-whois \
               --disable-servers
build      : |
    %make
install    : |
    %make_install

    # Cleanup
    rmdir -v $installdir/%libdir%/${package} \
             $installdir/%libdir%
