name       : inetutils
version    : 1.9.4
release    : 5
source     :
    - https://ftp.gnu.org/gnu/inetutils/inetutils-1.9.4.tar.xz : 849d96f136effdef69548a940e3e0ec0624fc0c81265296987986a0dd36ded37
homepage   : http://www.gnu.org/software/inetutils/
license    :
    - GPL-3.0
summary    : A collection of common network programs
component  : system.base
description: |
    A collection of common network programs, including:
    - An ftp client and server.
    - A telnet client and server.
    - An rsh client and server.
    - An rlogin client and server.
    - A tftp client and server.
    - And much more...
setup      : |
    %patch -p1 < $pkgfiles/0001-ifconfig-Force-use-of-proc-net-dev.patch
    %configure --disable-logger \
               --disable-whois \
               --disable-servers
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/%libdir%/${package}
